development:
  adapter: postgresql
  database: mrparser_development
  username: dev
  password:
  host: localhost
  encoding: utf8
production:
  adapter: postgresql
  database: mrparser_production
  username: dev
  password:
  host: localhost
  encoding: utf8
